# Generated by Django 5.1.2 on 2026-01-19 11:23

import django.db.models.deletion
import django.utils.timezone
import enterprise_asset_management.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Инфраструктура',
                'verbose_name_plural': 'Инфраструктура',
            },
        ),
        migrations.CreateModel(
            name='TransportVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Транспортные средства',
                'verbose_name_plural': 'Транспортные средства',
            },
        ),
        migrations.CreateModel(
            name='WorkEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.CharField(max_length=100, unique=True, verbose_name='Наименование, тип')),
                ('serial_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Заводской номер (s/n)')),
                ('measuring_device', models.BooleanField(default=False, verbose_name='Средство измерений')),
                ('next_calibration_date', models.DateField(blank=True, null=True, verbose_name='Дата плановой поверки')),
                ('workstation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Рабочее место')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Примечание / допустимая замена')),
                ('date_of_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время создания')),
                ('date_of_change', models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения')),
                ('version', models.CharField(blank=True, max_length=3, null=True, verbose_name='Версия')),
                ('version_diff', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Сравнение версий')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_equipment_author', to=settings.AUTH_USER_MODEL, verbose_name='Создатель (автор)')),
                ('current_responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_equipment_current_responsible', to=settings.AUTH_USER_MODEL, verbose_name='Текущий ответственный')),
                ('last_editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_equipment_last_editor', to=settings.AUTH_USER_MODEL, verbose_name='Последний редактор')),
            ],
            options={
                'verbose_name': 'Рабочее оборудование',
                'verbose_name_plural': 'Рабочее оборудование',
            },
        ),
        migrations.CreateModel(
            name='WorkEquipmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='work_equipment_files/', validators=[enterprise_asset_management.models.validate_file_size], verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата загрузки')),
                ('work_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='enterprise_asset_management.workequipment', verbose_name='Рабочее оборудование')),
            ],
            options={
                'verbose_name': 'Сопроводительный документ',
                'verbose_name_plural': 'Сопроводительные документы',
            },
        ),
    ]
