# Generated by Django 5.1.2 on 2026-01-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_asset_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workequipment',
            name='replacement_allowed',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Допустимая замена'),
        ),
        migrations.AlterField(
            model_name='workequipment',
            name='name_type',
            field=models.CharField(max_length=100, verbose_name='Наименование, тип'),
        ),
        migrations.AlterField(
            model_name='workequipment',
            name='note',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='workequipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Заводской номер (s/n)'),
        ),
        migrations.AlterField(
            model_name='workequipment',
            name='version',
            field=models.CharField(default='1', max_length=3, verbose_name='Версия'),
        ),
    ]
