# Generated by Django 5.1.8 on 2025-08-04 10:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisiontask',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения'),
        ),
        migrations.AlterField(
            model_name='revisiontask',
            name='date_of_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='taskfordesignwork',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения'),
        ),
        migrations.AlterField(
            model_name='taskfordesignwork',
            name='date_of_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='technicalassignment',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения'),
        ),
        migrations.AlterField(
            model_name='technicalassignment',
            name='date_of_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='workassignment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='workassignment',
            name='category',
            field=models.CharField(default='РЗ', max_length=100, verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='workassignment',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения'),
        ),
        migrations.AlterField(
            model_name='workassignment',
            name='date_of_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workassignment',
            name='deadline',
            field=models.DateField(verbose_name='срок выполнения'),
        ),
        migrations.AlterField(
            model_name='workassignment',
            name='last_editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited_workassignments', to=settings.AUTH_USER_MODEL, verbose_name='последний редактор'),
        ),
        migrations.AlterField(
            model_name='workassignment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='workassignment',
            name='result',
            field=models.CharField(max_length=100, verbose_name='результат'),
        ),
        migrations.AlterField(
            model_name='workassignment',
            name='result_description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='описание результата'),
        ),
        migrations.AlterField(
            model_name='workassignment',
            name='task',
            field=models.TextField(verbose_name='задача'),
        ),
        migrations.AlterField(
            model_name='workassignment',
            name='version',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='версия'),
        ),
    ]
