# Generated by Django 5.1.8 on 2025-08-04 10:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_revisiontask_date_of_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workassignment',
            name='date_of_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата и время создания'),
        ),
    ]
