# Generated by Django 5.1.8 on 2025-05-06 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_conformityassessment_designdocumentation_patenting_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Изделие', 'verbose_name_plural': 'Изделия'},
        ),
    ]
