# Generated by Django 5.1.8 on 2025-05-06 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Разработка', 'verbose_name_plural': 'Разраотки'},
        ),
    ]
