# Generated by Django 5.1.8 on 2025-08-04 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_workassignment_date_of_creation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisiontask',
            name='add_task_for_revision',
            field=models.FileField(blank=True, null=True, upload_to='revision_tasks/add/', verbose_name='приложение к ТЗ'),
        ),
        migrations.AlterField(
            model_name='revisiontask',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_revisions', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='revisiontask',
            name='category',
            field=models.CharField(default='ТЗ Д', max_length=100, verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='revisiontask',
            name='current_responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_revisions', to=settings.AUTH_USER_MODEL, verbose_name='текущий ответственный'),
        ),
        migrations.AlterField(
            model_name='revisiontask',
            name='develop_org',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='организация - разработчик'),
        ),
        migrations.AlterField(
            model_name='revisiontask',
            name='info_format',
            field=models.CharField(blank=True, default='оригинал ДЭ', max_length=100, null=True, verbose_name='формат'),
        ),
        migrations.AlterField(
            model_name='revisiontask',
            name='language',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='язык'),
        ),
        migrations.AlterField(
            model_name='revisiontask',
            name='last_editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited_revisions', to=settings.AUTH_USER_MODEL, verbose_name='последний редактор'),
        ),
        migrations.AlterField(
            model_name='revisiontask',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='revisiontask',
            name='pattern',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='шаблон'),
        ),
        migrations.AlterField(
            model_name='revisiontask',
            name='plan_for_revision',
            field=models.FileField(blank=True, null=True, upload_to='revision_tasks/plan/', verbose_name='план работ по ТЗ'),
        ),
        migrations.AlterField(
            model_name='revisiontask',
            name='priority',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='приоритет'),
        ),
        migrations.AlterField(
            model_name='revisiontask',
            name='related_documents',
            field=models.TextField(blank=True, null=True, verbose_name='связанный сопроводительные документы'),
        ),
        migrations.AlterField(
            model_name='revisiontask',
            name='status',
            field=models.CharField(default='Зарегистрирован', max_length=50, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='revisiontask',
            name='subscribers',
            field=models.TextField(blank=True, null=True, verbose_name='внешние и внутренние получатели'),
        ),
        migrations.AlterField(
            model_name='revisiontask',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='revision_tasks/', verbose_name='файл'),
        ),
        migrations.AlterField(
            model_name='revisiontask',
            name='validity_date',
            field=models.DateField(blank=True, null=True, verbose_name='срок действия'),
        ),
        migrations.AlterField(
            model_name='revisiontask',
            name='version',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='версия'),
        ),
        migrations.AlterField(
            model_name='revisiontask',
            name='version_diff',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='разница версий'),
        ),
        migrations.AlterField(
            model_name='taskfordesignwork',
            name='add_task_for_design_work',
            field=models.FileField(blank=True, null=True, upload_to='design_tasks/add/', verbose_name='приложение к ТЗ'),
        ),
        migrations.AlterField(
            model_name='taskfordesignwork',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_designtasks', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='taskfordesignwork',
            name='category',
            field=models.CharField(default='ТЗ ОКР', max_length=100, verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='taskfordesignwork',
            name='current_responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_designtasks', to=settings.AUTH_USER_MODEL, verbose_name='текущий ответственный'),
        ),
        migrations.AlterField(
            model_name='taskfordesignwork',
            name='develop_org',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='организация - разработчик'),
        ),
        migrations.AlterField(
            model_name='taskfordesignwork',
            name='info_format',
            field=models.CharField(blank=True, default='оригинал ДЭ', max_length=100, null=True, verbose_name='формат предоставления информации'),
        ),
        migrations.AlterField(
            model_name='taskfordesignwork',
            name='language',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='язык'),
        ),
        migrations.AlterField(
            model_name='taskfordesignwork',
            name='last_editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited_designtasks', to=settings.AUTH_USER_MODEL, verbose_name='последний редактор'),
        ),
        migrations.AlterField(
            model_name='taskfordesignwork',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='taskfordesignwork',
            name='pattern',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='шаблон'),
        ),
        migrations.AlterField(
            model_name='taskfordesignwork',
            name='plan_for_design_work',
            field=models.FileField(blank=True, null=True, upload_to='design_tasks/plan/', verbose_name='план работ по ТЗ'),
        ),
        migrations.AlterField(
            model_name='taskfordesignwork',
            name='priority',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='приоритет'),
        ),
        migrations.AlterField(
            model_name='taskfordesignwork',
            name='related_documents',
            field=models.TextField(blank=True, null=True, verbose_name='связанные сопроводительные документы'),
        ),
        migrations.AlterField(
            model_name='taskfordesignwork',
            name='status',
            field=models.CharField(default='Зарегистрирован', max_length=50, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='taskfordesignwork',
            name='subscribers',
            field=models.TextField(blank=True, null=True, verbose_name='внешние и внутренние получатели'),
        ),
        migrations.AlterField(
            model_name='taskfordesignwork',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='design_tasks/', verbose_name='загружаемый файл'),
        ),
        migrations.AlterField(
            model_name='taskfordesignwork',
            name='validity_date',
            field=models.DateField(blank=True, null=True, verbose_name='срок действия'),
        ),
        migrations.AlterField(
            model_name='taskfordesignwork',
            name='version',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='версия'),
        ),
        migrations.AlterField(
            model_name='taskfordesignwork',
            name='version_diff',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='разница версий'),
        ),
        migrations.AlterField(
            model_name='technicalassignment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='technicalassignment',
            name='current_responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_assignments', to=settings.AUTH_USER_MODEL, verbose_name='такущий ответственный'),
        ),
        migrations.AlterField(
            model_name='technicalassignment',
            name='last_editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited_assignments', to=settings.AUTH_USER_MODEL, verbose_name='последний редактор'),
        ),
        migrations.AlterField(
            model_name='technicalassignment',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='technicalassignment',
            name='version',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='версия'),
        ),
        migrations.AlterField(
            model_name='technicalassignment',
            name='version_diff',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='разница версий'),
        ),
        migrations.AlterField(
            model_name='workassignment',
            name='current_responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_workassignments', to=settings.AUTH_USER_MODEL, verbose_name='текущий ответственный'),
        ),
    ]
