# Generated by Django 5.1.8 on 2025-07-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_listtechnicalproposal_desig_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='desig_product',
            new_name='desig_document',
        ),
    ]
