# Generated by Django 5.1.8 on 2025-08-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_revisiontask_add_task_for_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisiontask',
            name='route',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Маршрут'),
        ),
        migrations.AddField(
            model_name='taskfordesignwork',
            name='route',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Маршрут'),
        ),
        migrations.AddField(
            model_name='technicalassignment',
            name='route',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Маршрут'),
        ),
        migrations.AddField(
            model_name='workassignment',
            name='route',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Маршрут'),
        ),
    ]
