# Generated by Django 5.1.8 on 2025-05-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Разработку', 'verbose_name_plural': 'Разработка'},
        ),
    ]
