# Generated by Django 5.1.8 on 2025-07-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_desig_product_post_desig_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listtechnicalproposal',
            name='desig_document',
            field=models.CharField(max_length=50, unique=True, verbose_name='Обозначение изделия'),
        ),
        migrations.AlterField(
            model_name='listtechnicalproposal',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='post',
            name='desig_document',
            field=models.CharField(max_length=50, verbose_name='Обозначение изделия'),
        ),
    ]
