# Generated by Django 5.1.8 on 2025-05-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='desig_product',
            new_name='design_product',
        ),
    ]
