# Generated by Django 5.1.8 on 2025-07-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_listtechnicalproposal_desig_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listtechnicalproposal',
            name='desig_document',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Обозначение изделия'),
        ),
        migrations.AlterField(
            model_name='listtechnicalproposal',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Наименование'),
        ),
    ]
