# Generated by Django 5.1.8 on 2025-05-14 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_desig_product_post_design_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('date_of_change', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('version_diff', models.TextField(blank=True, max_length=1000)),
                ('litera', models.CharField(default='П-', max_length=20)),
                ('trl', models.CharField(default='1-', max_length=10)),
                ('list_technical_proposal', models.CharField(blank=True, max_length=255, null=True)),
                ('general_drawing_product', models.CharField(blank=True, max_length=255, null=True)),
                ('electronic_model_product', models.CharField(blank=True, max_length=255, null=True)),
                ('general_electrical_circuit', models.CharField(blank=True, max_length=255, null=True)),
                ('product_software', models.CharField(blank=True, max_length=255, null=True)),
                ('report_technical_proposal', models.CharField(blank=True, max_length=255, null=True)),
                ('protocol_technical_proposal', models.CharField(blank=True, max_length=255, null=True)),
                ('general_drawing_unit', models.JSONField(blank=True, null=True)),
                ('electronic_model_unit', models.JSONField(blank=True, null=True)),
                ('drawing_part_unit', models.JSONField(blank=True, null=True)),
                ('electronic_model_part_unit', models.JSONField(blank=True, null=True)),
                ('drawing_part_product', models.JSONField(blank=True, null=True)),
                ('electronic_model_part_product', models.JSONField(blank=True, null=True)),
                ('add_report_technical_proposal', models.JSONField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tp_created_by', to=settings.AUTH_USER_MODEL)),
                ('current_responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tp_current_responsible', to=settings.AUTH_USER_MODEL)),
                ('last_editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tp_last_edited_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Техническое предложение',
                'verbose_name_plural': 'Технические предложения',
            },
        ),
    ]
