# Generated by Django 5.1.8 on 2025-07-17 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_listtechnicalproposal_desig_document_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='listtechnicalproposal',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='listtechnicalproposal',
            name='change_number',
            field=models.CharField(default='Изм. 1', max_length=20, verbose_name='Номер изменения'),
        ),
        migrations.AlterField(
            model_name='listtechnicalproposal',
            name='current_responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Текущий ответственный'),
        ),
        migrations.AlterField(
            model_name='listtechnicalproposal',
            name='desig_document',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='Обозначение изделия'),
        ),
        migrations.AlterField(
            model_name='listtechnicalproposal',
            name='info_format',
            field=models.CharField(choices=[('ДБ', 'ДБ'), ('ДЭ', 'ДЭ')], default='ДЭ', max_length=20, verbose_name='Формат представления информации'),
        ),
        migrations.AlterField(
            model_name='listtechnicalproposal',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Последний редактор'),
        ),
        migrations.AlterField(
            model_name='listtechnicalproposal',
            name='status',
            field=models.CharField(choices=[('Зарегистрирован', 'Зарегистрирован'), ('Рабочий вариант', 'Рабочий вариант'), ('Разработка', 'Разработка'), ('На согласовании', 'На согласовании'), ('Утвержден', 'Утвержден')], default='Зарегистрирован', max_length=30, verbose_name='Статус (состояние)'),
        ),
        migrations.AlterField(
            model_name='listtechnicalproposal',
            name='uploaded_file',
            field=models.FileField(default=0, upload_to='uploads/', verbose_name='Загружаемый файл'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='current_responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_posts', to=settings.AUTH_USER_MODEL, verbose_name='Текущий ответственный'),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_posts', to=settings.AUTH_USER_MODEL, verbose_name='Последний редактор'),
        ),
    ]
