# Generated by Django 5.1.8 on 2025-05-14 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_technicalproposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddReportTechnicalProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DrawingPartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DrawingPartUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DrawingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicModelPartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicModelPartUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicModelProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicModelUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralDrawingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralElectricalCircuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ListTechnicalProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProtocolTechnicalProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ReportTechnicalProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Разработка', 'verbose_name_plural': 'Разработки'},
        ),
        migrations.RemoveField(
            model_name='technicalproposal',
            name='add_report_technical_proposal',
        ),
        migrations.RemoveField(
            model_name='technicalproposal',
            name='drawing_part_product',
        ),
        migrations.RemoveField(
            model_name='technicalproposal',
            name='drawing_part_unit',
        ),
        migrations.RemoveField(
            model_name='technicalproposal',
            name='electronic_model_part_product',
        ),
        migrations.RemoveField(
            model_name='technicalproposal',
            name='electronic_model_part_unit',
        ),
        migrations.RemoveField(
            model_name='technicalproposal',
            name='electronic_model_unit',
        ),
        migrations.RemoveField(
            model_name='technicalproposal',
            name='general_drawing_unit',
        ),
        migrations.AlterField(
            model_name='technicalproposal',
            name='electronic_model_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.electronicmodelproduct'),
        ),
        migrations.AlterField(
            model_name='technicalproposal',
            name='general_drawing_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.generaldrawingproduct'),
        ),
        migrations.AlterField(
            model_name='technicalproposal',
            name='general_electrical_circuit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.generalelectricalcircuit'),
        ),
        migrations.AlterField(
            model_name='technicalproposal',
            name='list_technical_proposal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.listtechnicalproposal'),
        ),
        migrations.AlterField(
            model_name='technicalproposal',
            name='product_software',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.productsoftware'),
        ),
        migrations.AlterField(
            model_name='technicalproposal',
            name='protocol_technical_proposal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.protocoltechnicalproposal'),
        ),
        migrations.AlterField(
            model_name='technicalproposal',
            name='report_technical_proposal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.reporttechnicalproposal'),
        ),
        migrations.AddField(
            model_name='technicalproposal',
            name='add_report_technical_proposal',
            field=models.ManyToManyField(blank=True, to='blog.addreporttechnicalproposal'),
        ),
        migrations.AddField(
            model_name='technicalproposal',
            name='drawing_part_product',
            field=models.ManyToManyField(blank=True, to='blog.drawingpartproduct'),
        ),
        migrations.AddField(
            model_name='technicalproposal',
            name='drawing_part_unit',
            field=models.ManyToManyField(blank=True, to='blog.drawingpartunit'),
        ),
        migrations.AddField(
            model_name='technicalproposal',
            name='electronic_model_part_product',
            field=models.ManyToManyField(blank=True, to='blog.electronicmodelpartproduct'),
        ),
        migrations.AddField(
            model_name='technicalproposal',
            name='electronic_model_part_unit',
            field=models.ManyToManyField(blank=True, to='blog.electronicmodelpartunit'),
        ),
        migrations.AddField(
            model_name='technicalproposal',
            name='electronic_model_unit',
            field=models.ManyToManyField(blank=True, to='blog.electronicmodelunit'),
        ),
        migrations.AddField(
            model_name='technicalproposal',
            name='general_drawing_unit',
            field=models.ManyToManyField(blank=True, to='blog.drawingunit'),
        ),
    ]
