# Generated by Django 5.1.8 on 2025-07-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_listtechnicalproposal_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listtechnicalproposal',
            name='desig_document',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Обозначение изделия'),
        ),
    ]
