# Generated by Django 5.1.8 on 2025-07-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_listtechnicalproposal_desig_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listtechnicalproposal',
            name='desig_document',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='Обозначение изделия'),
        ),
    ]
