# Generated by Django 5.1.8 on 2025-05-26 10:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_addreporttechnicalproposal_drawingpartproduct_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listtechnicalproposal',
            name='application',
            field=models.CharField(default='Приложение не указано', max_length=50),
        ),
        migrations.AddField(
            model_name='listtechnicalproposal',
            name='approval_cycle',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listtechnicalproposal',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_list_tp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listtechnicalproposal',
            name='category',
            field=models.CharField(choices=[('ВПТ', 'Ведомость технического предложения'), ('ВО', 'Чертеж общего вида изделия'), ('ЭМИ', 'Электронная модель изделия')], default='ВПТ', max_length=50),
        ),
        migrations.AddField(
            model_name='listtechnicalproposal',
            name='change_number',
            field=models.CharField(default='Изм. 0', max_length=20),
        ),
        migrations.AddField(
            model_name='listtechnicalproposal',
            name='current_responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_list_tp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listtechnicalproposal',
            name='date_of_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='listtechnicalproposal',
            name='date_of_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='listtechnicalproposal',
            name='desig_document',
            field=models.CharField(default='TMP-0000', max_length=50),
        ),
        migrations.AddField(
            model_name='listtechnicalproposal',
            name='develop_org',
            field=models.CharField(default='ООО "СИСТЕМА"', max_length=100),
        ),
        migrations.AddField(
            model_name='listtechnicalproposal',
            name='file',
            field=models.CharField(default='Файл не указан', max_length=50),
        ),
        migrations.AddField(
            model_name='listtechnicalproposal',
            name='info_format',
            field=models.CharField(choices=[('ДБ КД', 'Бумажный КД'), ('ДЭ КД', 'Электронный КД'), ('ТДЭ', 'Текстовый электронный документ')], default='ДЭ', max_length=20),
        ),
        migrations.AddField(
            model_name='listtechnicalproposal',
            name='language',
            field=models.CharField(default='rus', max_length=10),
        ),
        migrations.AddField(
            model_name='listtechnicalproposal',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_list_tp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listtechnicalproposal',
            name='litera',
            field=models.CharField(default='П-', max_length=20),
        ),
        migrations.AddField(
            model_name='listtechnicalproposal',
            name='pattern',
            field=models.CharField(blank=True, default='ВПТ', max_length=50),
        ),
        migrations.AddField(
            model_name='listtechnicalproposal',
            name='primary_use',
            field=models.CharField(default='Нет данных', max_length=100),
        ),
        migrations.AddField(
            model_name='listtechnicalproposal',
            name='priority',
            field=models.CharField(blank=True, choices=[('Срочно', 'Срочно'), ('Высокий', 'Высокий'), ('Средний', 'Средний'), ('Низкий', 'Низкий')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='listtechnicalproposal',
            name='status',
            field=models.CharField(choices=[('Рабочий вариант', 'Рабочий вариант'), ('Разработка', 'Разработка'), ('На согласовании', 'На согласовании'), ('Утвержден', 'Утвержден')], default='Рабочий вариант', max_length=30),
        ),
        migrations.AddField(
            model_name='listtechnicalproposal',
            name='subscribers',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='listtechnicalproposal',
            name='trl',
            field=models.CharField(default='1-', max_length=10),
        ),
        migrations.AddField(
            model_name='listtechnicalproposal',
            name='validity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listtechnicalproposal',
            name='version',
            field=models.CharField(default='v1.0', max_length=6),
        ),
        migrations.AddField(
            model_name='listtechnicalproposal',
            name='version_diff',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='listtechnicalproposal',
            name='name',
            field=models.CharField(default='Ведомость ТП', max_length=100),
        ),
    ]
