# Generated by Django 5.1.8 on 2025-05-26 11:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_listtechnicalproposal_application_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generaldrawingproduct',
            name='application',
            field=models.CharField(default='Autodesk Inventor', max_length=50),
        ),
        migrations.AddField(
            model_name='generaldrawingproduct',
            name='approval_cycle',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generaldrawingproduct',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gd_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generaldrawingproduct',
            name='category',
            field=models.CharField(choices=[('ВПТ', 'Ведомость технического предложения'), ('ВО', 'Чертеж общего вида изделия'), ('ЭМИ', 'Электронная модель изделия'), ('Э6', 'Схема электрическая общая'), ('ПО ПТ', 'Программное обеспечение. Техническое предложение'), ('ВО СЕ', 'Чертеж общего вида сборочной единицы'), ('ЭМ СЕ', 'Электронная модель сборочной единицы'), ('ЧД СЕ', 'Чертеж детали сборочной единицы'), ('ЭМД СЕ', 'Электронная модель детали сборочной единицы'), ('ЧД ВО', 'Чертеж детали изделия'), ('ЭМД ВО', 'Электронная модель детали изделия'), ('ПЗ ПТ', 'Пояснительная записка. Техническое предложение'), ('ПЗ ПТ. Приложение', 'Пояснительная записка. Техническое предложение. Приложение'), ('Протокол ПТ', 'Протокол. Техническое предложение')], default='ВО', max_length=50),
        ),
        migrations.AddField(
            model_name='generaldrawingproduct',
            name='change_number',
            field=models.CharField(default='Изм. 1', max_length=50),
        ),
        migrations.AddField(
            model_name='generaldrawingproduct',
            name='current_responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gd_responsible', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generaldrawingproduct',
            name='date_of_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='generaldrawingproduct',
            name='date_of_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='generaldrawingproduct',
            name='desig_document',
            field=models.CharField(default='СИ.40522001.000.13ВО', max_length=50),
        ),
        migrations.AddField(
            model_name='generaldrawingproduct',
            name='develop_org',
            field=models.CharField(blank=True, default='ООО "СИСТЕМА"', max_length=100),
        ),
        migrations.AddField(
            model_name='generaldrawingproduct',
            name='file',
            field=models.CharField(default='Autodesk Inventor (.idw)', max_length=50),
        ),
        migrations.AddField(
            model_name='generaldrawingproduct',
            name='info_format',
            field=models.CharField(default='ДЭ', max_length=20),
        ),
        migrations.AddField(
            model_name='generaldrawingproduct',
            name='language',
            field=models.CharField(blank=True, default='rus', max_length=10),
        ),
        migrations.AddField(
            model_name='generaldrawingproduct',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gd_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generaldrawingproduct',
            name='litera',
            field=models.CharField(default='П-', max_length=20),
        ),
        migrations.AddField(
            model_name='generaldrawingproduct',
            name='pattern',
            field=models.CharField(blank=True, default='ВО ПТ', max_length=50),
        ),
        migrations.AddField(
            model_name='generaldrawingproduct',
            name='primary_use',
            field=models.CharField(default='СИ.40522001.000.13ВПТ', max_length=100),
        ),
        migrations.AddField(
            model_name='generaldrawingproduct',
            name='priority',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='generaldrawingproduct',
            name='status',
            field=models.CharField(default='На согласовании', max_length=50),
        ),
        migrations.AddField(
            model_name='generaldrawingproduct',
            name='subscribers',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='generaldrawingproduct',
            name='trl',
            field=models.CharField(default='1-', max_length=10),
        ),
        migrations.AddField(
            model_name='generaldrawingproduct',
            name='validity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generaldrawingproduct',
            name='version',
            field=models.CharField(default='v1.0', max_length=6),
        ),
        migrations.AddField(
            model_name='generaldrawingproduct',
            name='version_diff',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='generaldrawingproduct',
            name='name',
            field=models.CharField(default='ПАК СПМ 2.13 Чертеж общего вида изделия', max_length=100),
        ),
    ]
