# Generated by Django 5.1.8 on 2025-07-22 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_listtechnicalproposal_desig_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='addreporttechnicalproposal',
            name='language',
            field=models.CharField(choices=[('rus', 'rus'), ('eng', 'eng')], default='rus', max_length=10, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='addreporttechnicalproposal',
            name='uploaded_file',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='Загружаемый файл'),
        ),
        migrations.AlterField(
            model_name='addreporttechnicalproposal',
            name='version',
            field=models.CharField(default='1', max_length=6, verbose_name='Версия'),
        ),
        migrations.AlterField(
            model_name='drawingpartproduct',
            name='priority',
            field=models.CharField(blank=True, choices=[('Срочно', 'Срочно'), ('Высокий', 'Высокий'), ('Средний', 'Средний'), ('Низкий', 'Низкий')], default='', max_length=30, verbose_name='Приоритет в работе'),
        ),
        migrations.AlterField(
            model_name='drawingpartproduct',
            name='uploaded_file',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='Загружаемый файл'),
        ),
        migrations.AlterField(
            model_name='drawingpartproduct',
            name='version',
            field=models.CharField(default='1', max_length=6, verbose_name='Версия'),
        ),
        migrations.AlterField(
            model_name='drawingpartunit',
            name='priority',
            field=models.CharField(blank=True, choices=[('Срочно', 'Срочно'), ('Высокий', 'Высокий'), ('Средний', 'Средний'), ('Низкий', 'Низкий')], default='', max_length=30, verbose_name='Приоритет в работе'),
        ),
        migrations.AlterField(
            model_name='drawingpartunit',
            name='uploaded_file',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='Загружаемый файл'),
        ),
        migrations.AlterField(
            model_name='drawingpartunit',
            name='version',
            field=models.CharField(default='1', max_length=6, verbose_name='Версия'),
        ),
        migrations.AlterField(
            model_name='electronicmodelpartproduct',
            name='priority',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Приоритет в работе'),
        ),
        migrations.AlterField(
            model_name='electronicmodelpartproduct',
            name='uploaded_file',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='Загружаемый файл'),
        ),
        migrations.AlterField(
            model_name='electronicmodelpartproduct',
            name='version',
            field=models.CharField(default='1', max_length=6, verbose_name='Версия'),
        ),
        migrations.AlterField(
            model_name='electronicmodelpartunit',
            name='priority',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Приоритет в работе'),
        ),
        migrations.AlterField(
            model_name='electronicmodelpartunit',
            name='uploaded_file',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='Загружаемый файл'),
        ),
        migrations.AlterField(
            model_name='electronicmodelpartunit',
            name='version',
            field=models.CharField(default='1', max_length=6, verbose_name='Версия'),
        ),
        migrations.AlterField(
            model_name='electronicmodelproduct',
            name='priority',
            field=models.CharField(blank=True, choices=[('Срочно', 'Срочно'), ('Высокий', 'Высокий'), ('Средний', 'Средний'), ('Низкий', 'Низкий')], default='', max_length=30, verbose_name='Приоритет в работе'),
        ),
        migrations.AlterField(
            model_name='electronicmodelproduct',
            name='uploaded_file',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='Загружаемый файл'),
        ),
        migrations.AlterField(
            model_name='electronicmodelproduct',
            name='version',
            field=models.CharField(default='1', max_length=6, verbose_name='Версия'),
        ),
        migrations.AlterField(
            model_name='electronicmodelunit',
            name='priority',
            field=models.CharField(blank=True, choices=[('Срочно', 'Срочно'), ('Высокий', 'Высокий'), ('Средний', 'Средний'), ('Низкий', 'Низкий')], default='', max_length=30, verbose_name='Приоритет в работе'),
        ),
        migrations.AlterField(
            model_name='electronicmodelunit',
            name='uploaded_file',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='Загружаемый файл'),
        ),
        migrations.AlterField(
            model_name='electronicmodelunit',
            name='version',
            field=models.CharField(default='1', max_length=6, verbose_name='Версия'),
        ),
        migrations.AlterField(
            model_name='generaldrawingproduct',
            name='priority',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Приоритет в работе'),
        ),
        migrations.AlterField(
            model_name='generaldrawingproduct',
            name='uploaded_file',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='Загружаемый файл'),
        ),
        migrations.AlterField(
            model_name='generaldrawingproduct',
            name='version',
            field=models.CharField(default='1', max_length=6, verbose_name='Версия'),
        ),
        migrations.AlterField(
            model_name='generaldrawingunit',
            name='priority',
            field=models.CharField(blank=True, choices=[('Срочно', 'Срочно'), ('Высокий', 'Высокий'), ('Средний', 'Средний'), ('Низкий', 'Низкий')], default='', max_length=30, verbose_name='Приоритет в работе'),
        ),
        migrations.AlterField(
            model_name='generaldrawingunit',
            name='uploaded_file',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='Загружаемый файл'),
        ),
        migrations.AlterField(
            model_name='generaldrawingunit',
            name='version',
            field=models.CharField(default='1', max_length=6, verbose_name='Версия'),
        ),
        migrations.AlterField(
            model_name='generalelectricaldiagram',
            name='priority',
            field=models.CharField(blank=True, choices=[('Срочно', 'Срочно'), ('Высокий', 'Высокий'), ('Средний', 'Средний'), ('Низкий', 'Низкий')], default='', max_length=30, verbose_name='Приоритет в работе'),
        ),
        migrations.AlterField(
            model_name='generalelectricaldiagram',
            name='uploaded_file',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='Загружаемый файл'),
        ),
        migrations.AlterField(
            model_name='generalelectricaldiagram',
            name='version',
            field=models.CharField(default='1', max_length=6, verbose_name='Версия'),
        ),
        migrations.AlterField(
            model_name='listtechnicalproposal',
            name='priority',
            field=models.CharField(blank=True, choices=[('Срочно', 'Срочно'), ('Высокий', 'Высокий'), ('Средний', 'Средний'), ('Низкий', 'Низкий')], default='', max_length=30, verbose_name='Приоритет в работе'),
        ),
        migrations.AlterField(
            model_name='listtechnicalproposal',
            name='status',
            field=models.CharField(choices=[('Зарегистрирован', 'Зарегистрирован'), ('В разработке', 'В разработке'), ('На проверке', 'На проверке'), ('На утверждении', 'На утверждении'), ('Выпущен', 'Выпущен'), ('Заменен', 'Заменен'), ('Аннулирован', 'Аннулирован'), ('В архиве', 'В архиве')], default='Зарегистрирован', max_length=30, verbose_name='Статус (состояние)'),
        ),
        migrations.AlterField(
            model_name='listtechnicalproposal',
            name='uploaded_file',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='Загружаемый файл'),
        ),
        migrations.AlterField(
            model_name='listtechnicalproposal',
            name='version',
            field=models.CharField(default='1', max_length=6, verbose_name='Версия'),
        ),
        migrations.AlterField(
            model_name='protocoltechnicalproposal',
            name='priority',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Приоритет в работе'),
        ),
        migrations.AlterField(
            model_name='protocoltechnicalproposal',
            name='uploaded_file',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='Загружаемый файл'),
        ),
        migrations.AlterField(
            model_name='protocoltechnicalproposal',
            name='version',
            field=models.CharField(default='1', max_length=6, verbose_name='Версия'),
        ),
        migrations.AlterField(
            model_name='reporttechnicalproposal',
            name='current_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Текущий ответственный'),
        ),
        migrations.AlterField(
            model_name='reporttechnicalproposal',
            name='language',
            field=models.CharField(blank=True, choices=[('rus', 'rus'), ('eng', 'eng')], default='rus', max_length=10, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='reporttechnicalproposal',
            name='version',
            field=models.CharField(default='1', max_length=6, verbose_name='Версия'),
        ),
        migrations.AlterField(
            model_name='reworktask',
            name='change_description',
            field=models.TextField(blank=True, default='Стартовая версия', max_length=1000, null=True, verbose_name='Сравнение версий'),
        ),
        migrations.AlterField(
            model_name='reworktask',
            name='version',
            field=models.CharField(blank=True, default='1', max_length=6, verbose_name='Версия'),
        ),
        migrations.AlterField(
            model_name='softwareproduct',
            name='priority',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Приоритет в работе'),
        ),
        migrations.AlterField(
            model_name='softwareproduct',
            name='uploaded_file',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='Загружаемый файл'),
        ),
        migrations.AlterField(
            model_name='softwareproduct',
            name='version',
            field=models.CharField(default='1', max_length=6, verbose_name='Версия'),
        ),
        migrations.AlterField(
            model_name='template',
            name='change_description',
            field=models.TextField(blank=True, default='Стартовая версия', max_length=1000, null=True, verbose_name='Сравнение версий'),
        ),
        migrations.AlterField(
            model_name='template',
            name='version',
            field=models.CharField(blank=True, default='1', max_length=5, verbose_name='Версия'),
        ),
        migrations.AlterField(
            model_name='workplan',
            name='change_description',
            field=models.TextField(blank=True, default='Стартовая версия', max_length=1000, null=True, verbose_name='Сравнение версий'),
        ),
        migrations.AlterField(
            model_name='workplan',
            name='version',
            field=models.CharField(blank=True, default='1', max_length=6, verbose_name='Версия'),
        ),
    ]
