# Generated by Django 5.1.8 on 2025-05-27 09:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_generaldrawingproduct_application_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicmodelproduct',
            name='application',
            field=models.CharField(default='Autodesk Inventor', max_length=50),
        ),
        migrations.AddField(
            model_name='electronicmodelproduct',
            name='approval_cycle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='electronicmodelproduct',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electronicmodel_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='electronicmodelproduct',
            name='category',
            field=models.CharField(choices=[('ВПТ', 'Ведомость технического предложения'), ('ВО', 'Чертеж общего вида изделия'), ('ЭМИ', 'Электронная модель изделия')], default='ЭМИ', max_length=50),
        ),
        migrations.AddField(
            model_name='electronicmodelproduct',
            name='change_number',
            field=models.CharField(default='Изм. 1', max_length=20),
        ),
        migrations.AddField(
            model_name='electronicmodelproduct',
            name='current_responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electronicmodel_responsible', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='electronicmodelproduct',
            name='date_of_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='electronicmodelproduct',
            name='date_of_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='electronicmodelproduct',
            name='desig_document',
            field=models.CharField(default='СИ.40522001.000.13ЭМИ', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='electronicmodelproduct',
            name='develop_org',
            field=models.CharField(default='ООО "СИСТЕМА"', max_length=100),
        ),
        migrations.AddField(
            model_name='electronicmodelproduct',
            name='file',
            field=models.CharField(default='Autodesk Inventor (.iam)', max_length=50),
        ),
        migrations.AddField(
            model_name='electronicmodelproduct',
            name='info_format',
            field=models.CharField(default='ДЭ', max_length=20),
        ),
        migrations.AddField(
            model_name='electronicmodelproduct',
            name='language',
            field=models.CharField(default='rus', max_length=10),
        ),
        migrations.AddField(
            model_name='electronicmodelproduct',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electronicmodel_last_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='electronicmodelproduct',
            name='litera',
            field=models.CharField(default='П-', max_length=20),
        ),
        migrations.AddField(
            model_name='electronicmodelproduct',
            name='pattern',
            field=models.CharField(blank=True, default='ЭМИ ПТ', max_length=50),
        ),
        migrations.AddField(
            model_name='electronicmodelproduct',
            name='primary_use',
            field=models.CharField(default='СИ.40522001.000.13ВПТ', max_length=100),
        ),
        migrations.AddField(
            model_name='electronicmodelproduct',
            name='priority',
            field=models.CharField(blank=True, choices=[('Срочно', 'Срочно'), ('Высокий', 'Высокий'), ('Средний', 'Средний'), ('Низкий', 'Низкий')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='electronicmodelproduct',
            name='related_docs',
            field=models.TextField(blank=True, default='', verbose_name='Связанные сопроводительные документы'),
        ),
        migrations.AddField(
            model_name='electronicmodelproduct',
            name='status',
            field=models.CharField(choices=[('Рабочий вариант', 'Рабочий вариант'), ('Разработка', 'Разработка'), ('Проверка', 'Проверка'), ('Проверен', 'Проверен'), ('На согласовании', 'На согласовании'), ('Согласован', 'Согласован'), ('На утверждении', 'На утверждении'), ('Утвержден', 'Утвержден'), ('Отклонен', 'Отклонен'), ('Выпущен', 'Выпущен'), ('Заморожен', 'Заморожен'), ('Заменен', 'Заменен'), ('Заблокирован', 'Заблокирован'), ('Аннулирован', 'Аннулирован'), ('На пересмотре', 'На пересмотре'), ('Архив', 'Архив')], default='Рабочий вариант', max_length=50),
        ),
        migrations.AddField(
            model_name='electronicmodelproduct',
            name='subscribers',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='electronicmodelproduct',
            name='technical_proposal',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='electronic_model_product_link', to='blog.technicalproposal'),
        ),
        migrations.AddField(
            model_name='electronicmodelproduct',
            name='trl',
            field=models.CharField(choices=[('1', '1'), ('2-', '2-'), ('2', '2'), ('3-', '3-'), ('3', '3')], default='1-', max_length=10),
        ),
        migrations.AddField(
            model_name='electronicmodelproduct',
            name='validity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electronicmodelproduct',
            name='version',
            field=models.CharField(default='v1.0', max_length=6),
        ),
        migrations.AddField(
            model_name='electronicmodelproduct',
            name='version_diff',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='electronicmodelproduct',
            name='name',
            field=models.CharField(default='ПАК СПМ 2.13 Электронная модель изделия', max_length=100),
        ),
    ]
