# Generated by Django 5.1.8 on 2025-07-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_addreporttechnicalproposal_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporttechnicalproposal',
            name='litera',
        ),
        migrations.RemoveField(
            model_name='reporttechnicalproposal',
            name='trl',
        ),
        migrations.AddField(
            model_name='techtask',
            name='описание',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='reporttechnicalproposal',
            name='info_format',
            field=models.CharField(blank=True, choices=[('ДБ', 'ДБ'), ('ДЭ', 'ДЭ')], default='ДЭ', max_length=10, verbose_name='Формат представления информации'),
        ),
        migrations.AlterField(
            model_name='reporttechnicalproposal',
            name='status',
            field=models.CharField(choices=[('Зарегистрирован', 'Зарегистрирован'), ('В разработке', 'В разработке'), ('На проверке', 'На проверке'), ('На утверждении', 'На утверждении'), ('Выпущен', 'Выпущен'), ('Заменен', 'Заменен'), ('Аннулирован', 'Аннулирован'), ('В архиве', 'В архиве')], default='Зарегистрирован', max_length=30, verbose_name='Статус (состояние)'),
        ),
    ]
