# Generated by Django 5.1.8 on 2025-05-30 10:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_electronicmodelproduct_application_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicalproposal',
            name='general_electrical_circuit',
        ),
        migrations.CreateModel(
            name='GeneralElectricalDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Э6', 'Схема электрическая общая')], default='Э6', max_length=50)),
                ('name', models.CharField(default='ПАК СПМ 2.13 Схема электрическая общая', max_length=100)),
                ('desig_document', models.CharField(default='СИ.40522001.000.13Э6', max_length=50, unique=True)),
                ('info_format', models.CharField(choices=[('ДЭ', 'ДЭ'), ('ДЭ КД', 'ДЭ КД'), ('ТДЭ', 'ТДЭ'), ('ДБ КД', 'ДБ КД')], default='ДЭ', max_length=20)),
                ('primary_use', models.CharField(default='СИ.40522001.000.13ВПТ', max_length=100)),
                ('change_number', models.CharField(default='Изм. 1', max_length=20)),
                ('file', models.CharField(default='Autodesk AutoCAD (.dwg)', max_length=50)),
                ('application', models.CharField(default='Autodesk AutoCAD', max_length=50)),
                ('date_of_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_of_change', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Рабочий вариант', 'Рабочий вариант'), ('Разработка', 'Разработка'), ('Проверка', 'Проверка'), ('Проверен', 'Проверен'), ('На согласовании', 'На согласовании'), ('Согласован', 'Согласован'), ('На утверждении', 'На утверждении'), ('Утвержден', 'Утвержден'), ('Отклонен', 'Отклонен'), ('Выпущен', 'Выпущен'), ('Заморожен', 'Заморожен'), ('Заменен', 'Заменен'), ('Заблокирован', 'Заблокирован'), ('Аннулирован', 'Аннулирован'), ('На пересмотре', 'На пересмотре'), ('Архив', 'Архив')], default='На согласовании', max_length=30)),
                ('priority', models.CharField(blank=True, choices=[('Срочно', 'Срочно'), ('Высокий', 'Высокий'), ('Средний', 'Средний'), ('Низкий', 'Низкий')], default='', max_length=30)),
                ('approval_cycle', models.PositiveSmallIntegerField(default=0)),
                ('version', models.CharField(default='v1.0', max_length=6)),
                ('version_diff', models.TextField(blank=True, default='')),
                ('litera', models.CharField(default='П-', max_length=2)),
                ('trl', models.CharField(default='1-', max_length=10)),
                ('validity_date', models.DateField(blank=True, null=True)),
                ('subscribers', models.CharField(blank=True, default='', max_length=200)),
                ('related_documents', models.TextField(blank=True, default='')),
                ('pattern', models.CharField(blank=True, default='Э6 ПТ', max_length=50)),
                ('develop_org', models.CharField(default='ООО "СИСТЕМА"', max_length=100)),
                ('language', models.CharField(default='rus', max_length=10)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('current_responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='technicalproposal',
            name='general_electrical_diagram',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.generalelectricaldiagram'),
        ),
        migrations.DeleteModel(
            name='GeneralElectricalCircuit',
        ),
    ]
