# Generated by Django 5.1.8 on 2025-07-23 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_reporttechnicalproposal_litera_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='techtask',
            old_name='описание',
            new_name='description',
        ),
    ]
