# Generated by Django 5.1.8 on 2025-05-30 11:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_technicalproposal_general_electrical_circuit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicalproposal',
            name='product_software',
        ),
        migrations.CreateModel(
            name='SoftwareProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('ПО ПТ', 'Программное обеспечение. Техническое предложение')], default='ПО ПТ', max_length=50)),
                ('name', models.CharField(default='ПАК СПМ 2.13  Программное обеспечение. Техническое предложение', max_length=100)),
                ('desig_document', models.CharField(default='СИ.40522001.000.13ПО ПТ', max_length=50, unique=True)),
                ('info_format', models.CharField(default='ДЭ', max_length=30)),
                ('primary_use', models.CharField(default='СИ.40522001.000.13ВПТ', max_length=100)),
                ('change_number', models.CharField(default='Изм. 1', max_length=20)),
                ('file', models.CharField(default='Microsoft Office Word (.docx)', max_length=50)),
                ('application', models.CharField(default='Microsoft Office Word', max_length=50)),
                ('date_of_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_of_change', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Рабочий вариант', 'Рабочий вариант'), ('Разработка', 'Разработка'), ('Проверка', 'Проверка'), ('Проверен', 'Проверен'), ('На согласовании', 'На согласовании'), ('Согласован', 'Согласован'), ('На утверждении', 'На утверждении'), ('Утвержден', 'Утвержден'), ('Отклонен', 'Отклонен'), ('Выпущен', 'Выпущен'), ('Заморожен', 'Заморожен'), ('Заменен', 'Заменен'), ('Заблокирован', 'Заблокирован'), ('Аннулирован', 'Аннулирован'), ('На пересмотре', 'На пересмотре'), ('Архив', 'Архив')], default='Рабочий вариант', max_length=50)),
                ('priority', models.CharField(blank=True, default='', max_length=30)),
                ('approval_cycle', models.PositiveSmallIntegerField(default=0)),
                ('version', models.CharField(default='v1.0', max_length=6)),
                ('version_diff', models.TextField(blank=True, default='', max_length=1000)),
                ('litera', models.CharField(default='П-', max_length=20)),
                ('trl', models.CharField(default='1-', max_length=10)),
                ('validity_date', models.DateField(blank=True, null=True)),
                ('subscribers', models.CharField(blank=True, default='', max_length=200)),
                ('related_documents', models.TextField(blank=True, default='')),
                ('pattern', models.CharField(blank=True, default='ПО ПТ', max_length=50)),
                ('develop_org', models.CharField(default='ООО "СИСТЕМА"', max_length=100)),
                ('language', models.CharField(default='rus', max_length=10)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_author', to=settings.AUTH_USER_MODEL)),
                ('current_responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_responsible', to=settings.AUTH_USER_MODEL)),
                ('last_editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_last_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='technicalproposal',
            name='software_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.softwareproduct'),
        ),
        migrations.DeleteModel(
            name='ProductSoftware',
        ),
    ]
