# Generated by Django 5.1.8 on 2025-07-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_описание_techtask_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporttechnicalproposal',
            name='primary_use',
        ),
        migrations.AddField(
            model_name='reporttechnicalproposal',
            name='priority',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Приоритет в работе'),
        ),
        migrations.AddField(
            model_name='techtask',
            name='uploaded_file',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='Загружаемый файл'),
        ),
    ]
