# Generated by Django 5.1.8 on 2025-05-30 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_technicalproposal_product_software_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralDrawingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ВО СЕ', 'Чертеж общего вида сборочной единицы')], default='ВО СЕ', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('desig_document', models.CharField(max_length=50, unique=True)),
                ('info_format', models.CharField(choices=[('ДЭ КД', 'Электронный конструкторский документ'), ('ДЭ', 'Электронный документ')], default='ДЭ', max_length=20)),
                ('primary_use', models.CharField(max_length=100)),
                ('change_number', models.CharField(max_length=20)),
                ('file', models.CharField(max_length=50)),
                ('application', models.CharField(max_length=100)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('date_of_change', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Рабочий вариант', 'Рабочий вариант'), ('Разработка', 'Разработка'), ('Проверка', 'Проверка'), ('Проверен', 'Проверен'), ('На согласовании', 'На согласовании'), ('Согласован', 'Согласован'), ('На утверждении', 'На утверждении'), ('Утвержден', 'Утвержден'), ('Отклонен', 'Отклонен'), ('Выпущен', 'Выпущен'), ('Заморожен', 'Заморожен'), ('Заменен', 'Заменен'), ('Заблокирован', 'Заблокирован'), ('Аннулирован', 'Аннулирован'), ('На пересмотре', 'На пересмотре'), ('Архив', 'Архив')], default='Рабочий вариант', max_length=30)),
                ('priority', models.CharField(blank=True, choices=[('Срочно', 'Срочно'), ('Высокий', 'Высокий'), ('Средний', 'Средний'), ('Низкий', 'Низкий')], max_length=30, null=True)),
                ('approval_cycle', models.PositiveSmallIntegerField(default=0)),
                ('version', models.CharField(default='v1.0', max_length=6)),
                ('version_diff', models.TextField(blank=True)),
                ('litera', models.CharField(default='П-', max_length=2)),
                ('trl', models.CharField(choices=[('1-', '1-'), ('2-', '2-'), ('2', '2'), ('3-', '3-'), ('3', '3')], default='1-', max_length=10)),
                ('validity_date', models.DateField(blank=True, null=True)),
                ('subscribers', models.TextField(blank=True)),
                ('related_documents', models.TextField(blank=True)),
                ('pattern', models.CharField(blank=True, max_length=50)),
                ('develop_org', models.CharField(default='ООО "СИСТЕМА"', max_length=100)),
                ('language', models.CharField(choices=[('rus', 'rus'), ('eng', 'eng')], default='rus', max_length=10)),
                ('access_rights', models.CharField(default='7', max_length=50)),
                ('access_level', models.CharField(choices=[('О', 'общий'), ('К', 'конфиденциально'), ('С', 'секретно'), ('СС', 'совершенно секретно')], default='О', max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('current_responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('technical_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_drawing_units', to='blog.technicalproposal')),
            ],
        ),
        migrations.DeleteModel(
            name='DrawingUnit',
        ),
        migrations.AlterField(
            model_name='technicalproposal',
            name='general_drawing_unit',
            field=models.ManyToManyField(blank=True, to='blog.generaldrawingunit'),
        ),
    ]
