# Generated by Django 5.1.8 on 2025-07-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_reporttechnicalproposal_primary_use_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalproposal',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения'),
        ),
    ]
