# Generated by Django 5.1.8 on 2025-07-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_technicalproposal_date_of_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addreporttechnicalproposal',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения'),
        ),
        migrations.AlterField(
            model_name='drawingpartproduct',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения'),
        ),
        migrations.AlterField(
            model_name='drawingpartunit',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения'),
        ),
        migrations.AlterField(
            model_name='electronicmodelpartproduct',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения'),
        ),
        migrations.AlterField(
            model_name='electronicmodelpartunit',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения'),
        ),
        migrations.AlterField(
            model_name='electronicmodelproduct',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения'),
        ),
        migrations.AlterField(
            model_name='electronicmodelunit',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения'),
        ),
        migrations.AlterField(
            model_name='generaldrawingproduct',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения'),
        ),
        migrations.AlterField(
            model_name='generaldrawingunit',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения'),
        ),
        migrations.AlterField(
            model_name='generalelectricaldiagram',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения'),
        ),
        migrations.AlterField(
            model_name='listtechnicalproposal',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения'),
        ),
        migrations.AlterField(
            model_name='okrtask',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения'),
        ),
        migrations.AlterField(
            model_name='protocoltechnicalproposal',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения'),
        ),
        migrations.AlterField(
            model_name='reporttechnicalproposal',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения'),
        ),
        migrations.AlterField(
            model_name='softwareproduct',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения'),
        ),
        migrations.AlterField(
            model_name='techtask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения'),
        ),
    ]
