# Generated by Django 5.1.8 on 2025-07-23 12:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_addreporttechnicalproposal_date_of_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listtechnicalproposal',
            name='change_number',
            field=models.CharField(default='без изм', max_length=20, verbose_name='Номер изменения'),
        ),
        migrations.AlterField(
            model_name='okrtask',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='okrtask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения'),
        ),
    ]
