# Generated by Django 5.1.8 on 2025-06-02 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_electronicmodelunit_access_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicmodelunit',
            name='technical_proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electronic_model_units', to='blog.technicalproposal'),
        ),
    ]
