# Generated by Django 5.1.8 on 2025-06-02 08:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_electronicmodelunit_technical_proposal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='drawingpartunit',
            name='application',
            field=models.CharField(default='Autodesk Inventor', max_length=50),
        ),
        migrations.AddField(
            model_name='drawingpartunit',
            name='approval_cycle',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='drawingpartunit',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawing_partunit_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drawingpartunit',
            name='category',
            field=models.CharField(choices=[('ЧД СЕ', 'Чертеж детали сборочной единицы')], default='ЧД СЕ', max_length=20),
        ),
        migrations.AddField(
            model_name='drawingpartunit',
            name='change_number',
            field=models.CharField(default='Изм. 1', max_length=20),
        ),
        migrations.AddField(
            model_name='drawingpartunit',
            name='current_responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawing_partunit_responsible', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drawingpartunit',
            name='date_of_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='drawingpartunit',
            name='date_of_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='drawingpartunit',
            name='desig_document',
            field=models.CharField(default='1', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='drawingpartunit',
            name='develop_org',
            field=models.CharField(default='ООО "СИСТЕМА"', max_length=50),
        ),
        migrations.AddField(
            model_name='drawingpartunit',
            name='file',
            field=models.CharField(default='Autodesk Inventor (.idw)', max_length=50),
        ),
        migrations.AddField(
            model_name='drawingpartunit',
            name='info_format',
            field=models.CharField(choices=[('ДЭ КД', 'Электронный конструкторский документ'), ('ДЭ', 'Электронный документ')], default='ДЭ', max_length=10),
        ),
        migrations.AddField(
            model_name='drawingpartunit',
            name='language',
            field=models.CharField(default='rus', max_length=10),
        ),
        migrations.AddField(
            model_name='drawingpartunit',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawing_partunit_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drawingpartunit',
            name='litera',
            field=models.CharField(default='П-', max_length=2),
        ),
        migrations.AddField(
            model_name='drawingpartunit',
            name='pattern',
            field=models.CharField(blank=True, default='ЧД СЕ ПТ', max_length=50),
        ),
        migrations.AddField(
            model_name='drawingpartunit',
            name='primary_use',
            field=models.CharField(default='СИ.40522001.000.13ВПТ', max_length=100),
        ),
        migrations.AddField(
            model_name='drawingpartunit',
            name='priority',
            field=models.CharField(blank=True, choices=[('Срочно', 'Срочно'), ('Высокий', 'Высокий'), ('Средний', 'Средний'), ('Низкий', 'Низкий')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='drawingpartunit',
            name='related_documents',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='drawingpartunit',
            name='status',
            field=models.CharField(choices=[('Рабочий вариант', 'Рабочий вариант'), ('Разработка', 'Разработка'), ('Проверка', 'Проверка'), ('Проверен', 'Проверен'), ('На согласовании', 'На согласовании'), ('Согласован', 'Согласован'), ('На утверждении', 'На утверждении'), ('Утвержден', 'Утвержден'), ('Отклонен', 'Отклонен'), ('Выпущен', 'Выпущен'), ('Заморожен', 'Заморожен'), ('Заменен', 'Заменен'), ('Заблокирован', 'Заблокирован'), ('Аннулирован', 'Аннулирован'), ('На пересмотре', 'На пересмотре'), ('Архив', 'Архив')], default='На согласовании', max_length=30),
        ),
        migrations.AddField(
            model_name='drawingpartunit',
            name='subscribers',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='drawingpartunit',
            name='technical_proposal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drawing_part_units', to='blog.technicalproposal'),
        ),
        migrations.AddField(
            model_name='drawingpartunit',
            name='trl',
            field=models.CharField(default='1-', max_length=10),
        ),
        migrations.AddField(
            model_name='drawingpartunit',
            name='validity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drawingpartunit',
            name='version',
            field=models.CharField(default='v1.0', max_length=6),
        ),
        migrations.AddField(
            model_name='drawingpartunit',
            name='version_diff',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='drawingpartunit',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='drawingpartunit',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
