# Generated by Django 5.1.8 on 2025-06-02 09:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_drawingpartunit_application_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electronicmodelpartunit',
            options={'verbose_name': 'Электронная модель детали СЕ', 'verbose_name_plural': 'Электронные модели деталей СЕ'},
        ),
        migrations.AddField(
            model_name='electronicmodelpartunit',
            name='application',
            field=models.CharField(default='Autodesk Inventor', max_length=50),
        ),
        migrations.AddField(
            model_name='electronicmodelpartunit',
            name='approval_cycle',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='electronicmodelpartunit',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='electronic_model_part_units_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='electronicmodelpartunit',
            name='category',
            field=models.CharField(default='ЭМД СЕ', max_length=100),
        ),
        migrations.AddField(
            model_name='electronicmodelpartunit',
            name='change_number',
            field=models.CharField(default='Изм. 1', max_length=50),
        ),
        migrations.AddField(
            model_name='electronicmodelpartunit',
            name='current_responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='electronic_model_part_units_responsible', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='electronicmodelpartunit',
            name='date_of_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='electronicmodelpartunit',
            name='date_of_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='electronicmodelpartunit',
            name='desig_document',
            field=models.CharField(default=1, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='electronicmodelpartunit',
            name='develop_org',
            field=models.CharField(blank=True, default='ООО "СИСТЕМА"', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='electronicmodelpartunit',
            name='file',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='electronicmodelpartunit',
            name='info_format',
            field=models.CharField(default='ДЭ', max_length=50),
        ),
        migrations.AddField(
            model_name='electronicmodelpartunit',
            name='language',
            field=models.CharField(blank=True, default='rus', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='electronicmodelpartunit',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='electronic_model_part_units_edited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='electronicmodelpartunit',
            name='litera',
            field=models.CharField(default='П-', max_length=20),
        ),
        migrations.AddField(
            model_name='electronicmodelpartunit',
            name='pattern',
            field=models.CharField(blank=True, default='ЭМД СЕ ПТ', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='electronicmodelpartunit',
            name='primary_use',
            field=models.CharField(default='СИ.40522001.000.13ВПТ', max_length=100),
        ),
        migrations.AddField(
            model_name='electronicmodelpartunit',
            name='priority',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='electronicmodelpartunit',
            name='related_documents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electronicmodelpartunit',
            name='status',
            field=models.CharField(default='На согласовании', max_length=50),
        ),
        migrations.AddField(
            model_name='electronicmodelpartunit',
            name='subscribers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electronicmodelpartunit',
            name='technical_proposal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electronic_model_part_units', to='blog.technicalproposal'),
        ),
        migrations.AddField(
            model_name='electronicmodelpartunit',
            name='trl',
            field=models.CharField(default='1-', max_length=10),
        ),
        migrations.AddField(
            model_name='electronicmodelpartunit',
            name='validity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electronicmodelpartunit',
            name='version',
            field=models.CharField(default='v1.0', max_length=6),
        ),
        migrations.AddField(
            model_name='electronicmodelpartunit',
            name='version_diff',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electronicmodelpartunit',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='electronicmodelpartunit',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
