# Generated by Django 5.1.8 on 2025-06-09 10:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_drawingpartproduct_access_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicmodelpartproduct',
            name='application',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='electronicmodelpartproduct',
            name='approval_cycle',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='electronicmodelpartproduct',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empp_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='electronicmodelpartproduct',
            name='category',
            field=models.CharField(default='ЭМД ВО', max_length=50),
        ),
        migrations.AddField(
            model_name='electronicmodelpartproduct',
            name='change_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='electronicmodelpartproduct',
            name='current_responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empp_responsible', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='electronicmodelpartproduct',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='electronicmodelpartproduct',
            name='date_of_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='electronicmodelpartproduct',
            name='desig_document',
            field=models.CharField(default=1, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='electronicmodelpartproduct',
            name='develop_org',
            field=models.CharField(blank=True, default='ООО "СИСТЕМА"', max_length=100),
        ),
        migrations.AddField(
            model_name='electronicmodelpartproduct',
            name='file',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='electronicmodelpartproduct',
            name='info_format',
            field=models.CharField(blank=True, default='ДЭ', max_length=20),
        ),
        migrations.AddField(
            model_name='electronicmodelpartproduct',
            name='language',
            field=models.CharField(blank=True, default='rus', max_length=10),
        ),
        migrations.AddField(
            model_name='electronicmodelpartproduct',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empp_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='electronicmodelpartproduct',
            name='litera',
            field=models.CharField(default='П-', max_length=20),
        ),
        migrations.AddField(
            model_name='electronicmodelpartproduct',
            name='pattern',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='electronicmodelpartproduct',
            name='primary_use',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='electronicmodelpartproduct',
            name='priority',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='electronicmodelpartproduct',
            name='related_documents',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='electronicmodelpartproduct',
            name='status',
            field=models.CharField(default='Рабочий вариант', max_length=30),
        ),
        migrations.AddField(
            model_name='electronicmodelpartproduct',
            name='subscribers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='electronicmodelpartproduct',
            name='trl',
            field=models.CharField(default='1-', max_length=10),
        ),
        migrations.AddField(
            model_name='electronicmodelpartproduct',
            name='validity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electronicmodelpartproduct',
            name='version',
            field=models.CharField(default='v1.0', max_length=6),
        ),
        migrations.AddField(
            model_name='electronicmodelpartproduct',
            name='version_diff',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='electronicmodelpartproduct',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='listtechnicalproposal',
            name='desig_document',
            field=models.CharField(default=1, max_length=50, unique=True),
        ),
    ]
