# Generated by Django 5.1.8 on 2025-06-09 10:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_electronicmodelpartproduct_application_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttechnicalproposal',
            name='access_level',
            field=models.CharField(choices=[('О', 'Общий'), ('К', 'Конфиденциально'), ('С', 'Секретно'), ('СС', 'Совершенно секретно')], default='О', max_length=30),
        ),
        migrations.AddField(
            model_name='reporttechnicalproposal',
            name='application',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='reporttechnicalproposal',
            name='approval_cycle',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reporttechnicalproposal',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_technical_proposal_authors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporttechnicalproposal',
            name='category',
            field=models.CharField(choices=[('ПЗ ПТ', 'Пояснительная записка. Техническое предложение')], default='ПЗ ПТ', max_length=50),
        ),
        migrations.AddField(
            model_name='reporttechnicalproposal',
            name='current_responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_technical_proposal_responsibles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporttechnicalproposal',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reporttechnicalproposal',
            name='date_of_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reporttechnicalproposal',
            name='desig_document',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reporttechnicalproposal',
            name='develop_org',
            field=models.CharField(blank=True, choices=[('ООО "СИСТЕМА"', 'ООО "СИСТЕМА"')], default='ООО "СИСТЕМА"', max_length=100),
        ),
        migrations.AddField(
            model_name='reporttechnicalproposal',
            name='file',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='reporttechnicalproposal',
            name='info_format',
            field=models.CharField(blank=True, choices=[('ДБ', 'ДБ КД'), ('ДЭ', 'ДЭ КД'), ('ТДЭ', 'ТДЭ')], default='ДЭ', max_length=10),
        ),
        migrations.AddField(
            model_name='reporttechnicalproposal',
            name='language',
            field=models.CharField(blank=True, choices=[('rus', 'Русский'), ('eng', 'Английский')], default='rus', max_length=10),
        ),
        migrations.AddField(
            model_name='reporttechnicalproposal',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_technical_proposal_editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporttechnicalproposal',
            name='litera',
            field=models.CharField(default='П-', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='reporttechnicalproposal',
            name='pattern',
            field=models.CharField(blank=True, default='ПЗ ПТ', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reporttechnicalproposal',
            name='permission',
            field=models.CharField(choices=[('0', 'Ничего не разрешено'), ('1', 'Исполнение'), ('2', 'Запись'), ('3', 'Запись и исполнение'), ('4', 'Чтение'), ('5', 'Чтение и исполнение'), ('6', 'Чтение и запись'), ('7', 'Чтение, запись и исполнение')], default='7', max_length=2),
        ),
        migrations.AddField(
            model_name='reporttechnicalproposal',
            name='primary_use',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reporttechnicalproposal',
            name='priority',
            field=models.CharField(blank=True, choices=[('Срочно', 'Срочно'), ('Высокий', 'Высокий'), ('Средний', 'Средний'), ('Низкий', 'Низкий')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='reporttechnicalproposal',
            name='related_documents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporttechnicalproposal',
            name='status',
            field=models.CharField(choices=[('Рабочий вариант', 'Рабочий вариант'), ('Разработка', 'Разработка'), ('Проверка', 'Проверка'), ('Проверен', 'Проверен'), ('На согласовании', 'На согласовании'), ('Согласован', 'Согласован'), ('На утверждении', 'На утверждении'), ('Утвержден', 'Утвержден'), ('Отклонен', 'Отклонен'), ('Выпущен', 'Выпущен'), ('Заморожен', 'Заморожен'), ('Заменен', 'Заменен'), ('Заблокирован', 'Заблокирован'), ('Аннулирован', 'Аннулирован'), ('На пересмотре', 'На пересмотре'), ('Архив', 'Архив')], default='Рабочий вариант', max_length=50),
        ),
        migrations.AddField(
            model_name='reporttechnicalproposal',
            name='subscribers',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reporttechnicalproposal',
            name='trl',
            field=models.CharField(default='1-', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='reporttechnicalproposal',
            name='validity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporttechnicalproposal',
            name='version',
            field=models.CharField(default='v1.0', max_length=6),
        ),
        migrations.AddField(
            model_name='reporttechnicalproposal',
            name='version_diff',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reporttechnicalproposal',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='reporttechnicalproposal',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
