# Generated by Django 5.1.8 on 2025-06-09 12:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_addreporttechnicalproposal_access_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protocoltechnicalproposal',
            options={'verbose_name': 'Протокол. Техническое предложение', 'verbose_name_plural': 'Протоколы. Технические предложения'},
        ),
        migrations.AddField(
            model_name='protocoltechnicalproposal',
            name='access_level',
            field=models.CharField(default='О', max_length=30),
        ),
        migrations.AddField(
            model_name='protocoltechnicalproposal',
            name='application',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='protocoltechnicalproposal',
            name='approval_cycle',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='protocoltechnicalproposal',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocol_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='protocoltechnicalproposal',
            name='category',
            field=models.CharField(default='Протокол ПТ', help_text='Категория документа', max_length=100),
        ),
        migrations.AddField(
            model_name='protocoltechnicalproposal',
            name='current_responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocol_responsible', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='protocoltechnicalproposal',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='protocoltechnicalproposal',
            name='date_of_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='protocoltechnicalproposal',
            name='desig_document',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='protocoltechnicalproposal',
            name='develop_org',
            field=models.CharField(blank=True, default='ООО "СИСТЕМА"', max_length=100),
        ),
        migrations.AddField(
            model_name='protocoltechnicalproposal',
            name='file',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='protocoltechnicalproposal',
            name='info_format',
            field=models.CharField(blank=True, default='ДЭ', max_length=20),
        ),
        migrations.AddField(
            model_name='protocoltechnicalproposal',
            name='language',
            field=models.CharField(blank=True, default='rus', max_length=10),
        ),
        migrations.AddField(
            model_name='protocoltechnicalproposal',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocol_edited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='protocoltechnicalproposal',
            name='litera',
            field=models.CharField(default='П-', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='protocoltechnicalproposal',
            name='pattern',
            field=models.CharField(blank=True, default='Протокол ПТ', max_length=100),
        ),
        migrations.AddField(
            model_name='protocoltechnicalproposal',
            name='permission',
            field=models.CharField(default='7', max_length=50),
        ),
        migrations.AddField(
            model_name='protocoltechnicalproposal',
            name='primary_use',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='protocoltechnicalproposal',
            name='priority',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='protocoltechnicalproposal',
            name='related_documents',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='protocoltechnicalproposal',
            name='status',
            field=models.CharField(default='На согласовании', max_length=30),
        ),
        migrations.AddField(
            model_name='protocoltechnicalproposal',
            name='subscribers',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='protocoltechnicalproposal',
            name='trl',
            field=models.CharField(default='1-', max_length=10),
        ),
        migrations.AddField(
            model_name='protocoltechnicalproposal',
            name='validity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocoltechnicalproposal',
            name='version',
            field=models.CharField(default='v1.0', max_length=6),
        ),
        migrations.AddField(
            model_name='protocoltechnicalproposal',
            name='version_diff',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='protocoltechnicalproposal',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='protocoltechnicalproposal',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
