# Generated by Django 5.1.8 on 2025-06-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_protocoltechnicalproposal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocoltechnicalproposal',
            name='uploaded_file',
            field=models.FileField(default=0, upload_to='uploads/'),
        ),
    ]
