# Generated by Django 5.1.8 on 2025-06-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_protocoltechnicalproposal_uploaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='addreporttechnicalproposal',
            name='uploaded_file',
            field=models.FileField(default=0, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='drawingpartproduct',
            name='uploaded_file',
            field=models.FileField(default=0, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='drawingpartunit',
            name='uploaded_file',
            field=models.FileField(default=0, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='electronicmodelpartproduct',
            name='uploaded_file',
            field=models.FileField(default=0, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='electronicmodelpartunit',
            name='uploaded_file',
            field=models.FileField(default=0, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='electronicmodelproduct',
            name='uploaded_file',
            field=models.FileField(default=0, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='electronicmodelunit',
            name='uploaded_file',
            field=models.FileField(default=0, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='generaldrawingproduct',
            name='uploaded_file',
            field=models.FileField(default=0, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='generaldrawingunit',
            name='uploaded_file',
            field=models.FileField(default=0, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='generalelectricaldiagram',
            name='uploaded_file',
            field=models.FileField(default=0, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='listtechnicalproposal',
            name='uploaded_file',
            field=models.FileField(default=0, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='reporttechnicalproposal',
            name='uploaded_file',
            field=models.FileField(default=0, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='uploaded_file',
            field=models.FileField(default=0, upload_to='uploads/'),
        ),
    ]
