# Generated by Django 5.1.8 on 2025-06-26 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_addreporttechnicalproposal_uploaded_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='technical_proposal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Post', to='blog.technicalproposal', verbose_name='Техническое предложение (литера П)'),
        ),
    ]
