# Generated by Django 5.1.8 on 2025-06-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_post_technical_proposal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addreporttechnicalproposal',
            options={'verbose_name': 'Добавить пояснительная записка Технического предложения', 'verbose_name_plural': 'Добавить пояснительные записки Технического предложения'},
        ),
        migrations.AlterModelOptions(
            name='drawingpartproduct',
            options={'verbose_name': 'Чертеж детали изделия', 'verbose_name_plural': 'Чертежи детали изделия'},
        ),
        migrations.AlterModelOptions(
            name='electronicmodelpartproduct',
            options={'verbose_name': 'Электронная модель детали изделия', 'verbose_name_plural': 'Электронные модели детали изделия'},
        ),
        migrations.AlterModelOptions(
            name='listtechnicalproposal',
            options={'verbose_name': 'Ведомость технического предложения', 'verbose_name_plural': 'Ведомости технического предложения'},
        ),
    ]
