# Generated by Django 5.1.8 on 2025-06-26 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_addreporttechnicalproposal_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drawingpartunit',
            options={'verbose_name': 'Чертеж детали сборочной единицы', 'verbose_name_plural': 'Чертежи детали сборочной единицы'},
        ),
        migrations.AlterModelOptions(
            name='electronicmodelproduct',
            options={'verbose_name': 'Электронная модель продукта', 'verbose_name_plural': 'Электронные модели продукта'},
        ),
        migrations.AlterModelOptions(
            name='electronicmodelunit',
            options={'verbose_name': 'Электронная модель сборочной единицы', 'verbose_name_plural': 'Электронные модели сборочной единицы'},
        ),
        migrations.AlterModelOptions(
            name='generaldrawingproduct',
            options={'verbose_name': 'Чертеж общего вида изделия', 'verbose_name_plural': 'Чертежи общего вида изделия'},
        ),
        migrations.AlterModelOptions(
            name='generaldrawingunit',
            options={'verbose_name': 'Чертеж общего вида сборочной единицы', 'verbose_name_plural': 'Чертежи общего вида сборочной еденицы'},
        ),
        migrations.AlterModelOptions(
            name='generalelectricaldiagram',
            options={'verbose_name': 'Схема электрическая общая', 'verbose_name_plural': 'Схемы электрические общие'},
        ),
        migrations.AlterModelOptions(
            name='reporttechnicalproposal',
            options={'verbose_name': 'Пояснительна записка Технического предложения', 'verbose_name_plural': 'Пояснительные записки Технического предложения'},
        ),
        migrations.AlterModelOptions(
            name='softwareproduct',
            options={'verbose_name': 'Программное обеспечение Технического предложения', 'verbose_name_plural': 'Программные обеспечения Технического предложения'},
        ),
    ]
