# Generated by Django 5.1.8 on 2025-06-27 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_alter_drawingpartunit_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='technical_design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='DesignDocumentation',
            new_name='prelim_design',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='design_documentation',
            new_name='prelim_design',
        ),
        migrations.AddField(
            model_name='post',
            name='technical_design',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.technical_design'),
        ),
    ]
