# Generated by Django 5.1.8 on 2025-06-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_technical_design_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addreporttechnicalproposal',
            name='version',
            field=models.CharField(default='1.0', max_length=6),
        ),
        migrations.AlterField(
            model_name='drawingpartproduct',
            name='version',
            field=models.CharField(default='1.0', max_length=6),
        ),
        migrations.AlterField(
            model_name='drawingpartunit',
            name='version',
            field=models.CharField(default='1.0', max_length=6),
        ),
        migrations.AlterField(
            model_name='electronicmodelpartproduct',
            name='version',
            field=models.CharField(default='1.0', max_length=6),
        ),
        migrations.AlterField(
            model_name='electronicmodelpartunit',
            name='version',
            field=models.CharField(default='1.0', max_length=6),
        ),
        migrations.AlterField(
            model_name='electronicmodelproduct',
            name='version',
            field=models.CharField(default='1.0', max_length=6),
        ),
        migrations.AlterField(
            model_name='electronicmodelunit',
            name='version',
            field=models.CharField(default='1.0', max_length=6),
        ),
        migrations.AlterField(
            model_name='generaldrawingproduct',
            name='version',
            field=models.CharField(default='1.0', max_length=6),
        ),
        migrations.AlterField(
            model_name='generaldrawingunit',
            name='version',
            field=models.CharField(default='1.0', max_length=6),
        ),
        migrations.AlterField(
            model_name='generalelectricaldiagram',
            name='version',
            field=models.CharField(default='1.0', max_length=6),
        ),
        migrations.AlterField(
            model_name='listtechnicalproposal',
            name='version',
            field=models.CharField(default='1.0', max_length=6),
        ),
        migrations.AlterField(
            model_name='protocoltechnicalproposal',
            name='version',
            field=models.CharField(default='1.0', max_length=6),
        ),
        migrations.AlterField(
            model_name='reporttechnicalproposal',
            name='version',
            field=models.CharField(default='1.0', max_length=6),
        ),
        migrations.AlterField(
            model_name='softwareproduct',
            name='version',
            field=models.CharField(default='1.0', max_length=6),
        ),
    ]
