# Generated by Django 5.1.8 on 2025-06-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_alter_addreporttechnicalproposal_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addreporttechnicalproposal',
            name='version_diff',
            field=models.TextField(blank=True, default='Стартовая версия', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='drawingpartproduct',
            name='version_diff',
            field=models.TextField(blank=True, default='Стартовая версия'),
        ),
        migrations.AlterField(
            model_name='drawingpartunit',
            name='version_diff',
            field=models.TextField(blank=True, default='Стартовая версия', max_length=1000),
        ),
        migrations.AlterField(
            model_name='electronicmodelpartproduct',
            name='version_diff',
            field=models.TextField(blank=True, default='Стартовая версия'),
        ),
        migrations.AlterField(
            model_name='electronicmodelpartunit',
            name='version_diff',
            field=models.TextField(blank=True, default='Стартовая версия', null=True),
        ),
        migrations.AlterField(
            model_name='electronicmodelproduct',
            name='version_diff',
            field=models.TextField(blank=True, default='Стартовая версия'),
        ),
        migrations.AlterField(
            model_name='electronicmodelunit',
            name='version_diff',
            field=models.TextField(blank=True, default='Стартовая версия'),
        ),
        migrations.AlterField(
            model_name='generaldrawingproduct',
            name='version_diff',
            field=models.TextField(blank=True, default='Стартовая версия', max_length=1000),
        ),
        migrations.AlterField(
            model_name='generaldrawingunit',
            name='version_diff',
            field=models.TextField(blank=True, default='Стартовая версия'),
        ),
        migrations.AlterField(
            model_name='generalelectricaldiagram',
            name='version_diff',
            field=models.TextField(blank=True, default='Стартовая версия'),
        ),
        migrations.AlterField(
            model_name='listtechnicalproposal',
            name='version_diff',
            field=models.TextField(blank=True, default='Стартовая версия'),
        ),
        migrations.AlterField(
            model_name='post',
            name='version_diff',
            field=models.TextField(blank=True, default='Стартовая версия', max_length=1000),
        ),
        migrations.AlterField(
            model_name='protocoltechnicalproposal',
            name='version_diff',
            field=models.TextField(blank=True, default='Стартовая версия', max_length=1000),
        ),
        migrations.AlterField(
            model_name='reporttechnicalproposal',
            name='version_diff',
            field=models.TextField(blank=True, default='Стартовая версия', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='softwareproduct',
            name='version_diff',
            field=models.TextField(blank=True, default='Стартовая версия', max_length=1000),
        ),
        migrations.AlterField(
            model_name='technicalproposal',
            name='version_diff',
            field=models.TextField(blank=True, default='Стартовая версия', max_length=1000),
        ),
    ]
