# Generated by Django 5.1.8 on 2025-06-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_alter_addreporttechnicalproposal_version_diff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='version',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='technicalproposal',
            name='version',
            field=models.CharField(blank=True, default='1', max_length=20),
        ),
    ]
