# Generated by Django 5.1.8 on 2025-06-27 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_alter_post_version_alter_technicalproposal_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addreporttechnicalproposal',
            name='desig_document',
        ),
        migrations.RemoveField(
            model_name='reporttechnicalproposal',
            name='desig_document',
        ),
    ]
