# Generated by Django 5.1.8 on 2025-06-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_remove_addreporttechnicalproposal_desig_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addreporttechnicalproposal',
            name='info_format',
            field=models.CharField(blank=True, choices=[('ДБ', 'ДБ КД'), ('ДЭ', 'ДЭ КД')], default='ДЭ', max_length=10),
        ),
    ]
