# Generated by Django 5.1.8 on 2025-06-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_alter_addreporttechnicalproposal_info_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listtechnicalproposal',
            name='info_format',
            field=models.CharField(choices=[('ДБ', 'ДБ'), ('ДЭ', 'ДЭ')], default='ДЭ', max_length=20),
        ),
    ]
