# Generated by Django 5.1.8 on 2025-06-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_alter_listtechnicalproposal_info_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaldrawingunit',
            name='info_format',
            field=models.CharField(choices=[('ДБ', 'ДБ'), ('ДЭ', 'ДЭ')], default='ДЭ', max_length=20),
        ),
        migrations.AlterField(
            model_name='generalelectricaldiagram',
            name='info_format',
            field=models.CharField(choices=[('ДЭ', 'ДЭ'), ('ДБ', 'ДБ')], default='ДЭ', max_length=20),
        ),
    ]
