# Generated by Django 5.1.8 on 2025-06-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_alter_generaldrawingunit_info_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addreporttechnicalproposal',
            name='category',
            field=models.CharField(default='ПЗ ПТ. Приложение', max_length=50),
        ),
        migrations.AlterField(
            model_name='drawingpartproduct',
            name='category',
            field=models.CharField(default='ЧД ВО', max_length=50),
        ),
        migrations.AlterField(
            model_name='drawingpartunit',
            name='category',
            field=models.CharField(default='ЧД СЕ', max_length=20),
        ),
        migrations.AlterField(
            model_name='electronicmodelproduct',
            name='category',
            field=models.CharField(default='ЭМИ', max_length=50),
        ),
        migrations.AlterField(
            model_name='electronicmodelunit',
            name='category',
            field=models.CharField(default='ЭМ СЕ', max_length=50),
        ),
        migrations.AlterField(
            model_name='generaldrawingproduct',
            name='category',
            field=models.CharField(default='ВО', max_length=50),
        ),
        migrations.AlterField(
            model_name='generaldrawingunit',
            name='category',
            field=models.CharField(default='ВО СЕ', max_length=50),
        ),
        migrations.AlterField(
            model_name='generalelectricaldiagram',
            name='category',
            field=models.CharField(default='Э6', max_length=50),
        ),
        migrations.AlterField(
            model_name='listtechnicalproposal',
            name='category',
            field=models.CharField(default='ВПТ', max_length=50),
        ),
        migrations.AlterField(
            model_name='reporttechnicalproposal',
            name='category',
            field=models.CharField(default='ПЗ ПТ', max_length=50),
        ),
        migrations.AlterField(
            model_name='softwareproduct',
            name='category',
            field=models.CharField(default='ПО ПТ', max_length=50),
        ),
    ]
