# Generated by Django 5.1.8 on 2025-06-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_alter_addreporttechnicalproposal_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listtechnicalproposal',
            name='name',
            field=models.CharField(editable=False, max_length=150),
        ),
    ]
