# Generated by Django 5.1.8 on 2025-06-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_alter_listtechnicalproposal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listtechnicalproposal',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
