# Generated by Django 5.1.8 on 2025-07-07 09:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_alter_listtechnicalproposal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_of_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_of_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
