# Generated by Django 5.1.8 on 2025-07-07 09:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_alter_post_date_of_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalproposal',
            name='date_of_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='technicalproposal',
            name='date_of_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
