# Generated by Django 5.1.8 on 2025-07-07 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_alter_technicalproposal_date_of_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalproposal',
            name='list_technical_proposal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.listtechnicalproposal'),
        ),
    ]
