# Generated by Django 5.1.8 on 2025-07-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_alter_technicalproposal_litera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='litera',
            field=models.CharField(choices=[('П-', 'П-'), ('П', 'П')], default='П-', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='trl',
            field=models.CharField(choices=[('1-', '1-'), ('1', '1')], default='1-', max_length=10),
        ),
    ]
