# Generated by Django 5.1.8 on 2025-07-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_alter_post_litera_alter_post_trl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listtechnicalproposal',
            name='primary_use',
        ),
        migrations.AlterField(
            model_name='listtechnicalproposal',
            name='status',
            field=models.CharField(choices=[('Зарегистрирован', 'Зарегистрирован'), ('Рабочий вариант', 'Рабочий вариант'), ('Разработка', 'Разработка'), ('На согласовании', 'На согласовании'), ('Утвержден', 'Утвержден')], default='Зарегистрирован', max_length=30),
        ),
    ]
