# Generated by Django 4.2.23 on 2025-07-10 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании')),
                ('revenue_for_last_year', models.DecimalField(decimal_places=2, help_text='Миллиард рублей', max_digits=12, verbose_name='Выручка за последний год')),
                ('length_of_electrical_network_km', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Длина сетей, км')),
                ('quantity_of_technical_transformer_pcs', models.PositiveIntegerField(verbose_name='Количество ТП, шт')),
                ('address', models.TextField(verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
                'ordering': ['name_of_company'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('date_of_last_change', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('date_of_next_activity', models.DateField(verbose_name='Дата следующей активности')),
                ('status', models.CharField(choices=[('подготовлен_звонок', 'Подготовлен звонок'), ('сделан_звонок', 'Сделан звонок'), ('назначена_встреча', 'Назначена встреча'), ('прошла_встреча', 'Прошла встреча'), ('достигнута_договоренность', 'Достигнута договоренность'), ('готовится_договор', 'Готовится договор'), ('заключен_договор', 'Заключен договор'), ('исполнена_поставка', 'Исполнена поставка'), ('выполнен_монтаж', 'Выполнен монтаж'), ('идет_гарантийный_срок', 'Идет гарантийный срок'), ('послегарантийная_работа', 'Послегарантийная работа')], max_length=50, verbose_name='Состояние')),
                ('deal_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма сделки')),
                ('quantity_of_all_product', models.PositiveIntegerField(default=1, verbose_name='Количество всех продуктов, шт')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('shipping_address', models.TextField(verbose_name='Адрес отгрузки')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='сделки', to='crm.customer', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Prouct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_product', models.CharField(max_length=255, verbose_name='Название')),
                ('end_customer_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена для конечного заказчика')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name_of_product'],
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Decision_maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('city_of_location', models.CharField(max_length=100, verbose_name='Город местонахождения')),
                ('function', models.IntegerField(choices=[(0, 'директор'), (1, 'главный инженер'), (2, 'технический специалист')], default=0)),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=54, unique=True, verbose_name='Почта')),
                ('telegram', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телеграм')),
                ('description_and_impression', models.TextField(blank=True, null=True, verbose_name='Описание и впечатления')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='лпр_листы', to='crm.customer', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'ЛПР',
                'verbose_name_plural': 'ЛПР',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Deal_stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_step', models.DateField(verbose_name='Дата начала этапа')),
                ('end_date_step', models.DateField(verbose_name='Дата конца этапа')),
                ('status', models.CharField(choices=[('подготовлен_звонок', 'Подготовлен звонок'), ('сделан_звонок', 'Сделан звонок'), ('назначена_встреча', 'Назначена встреча'), ('прошла_встреча', 'Прошла встреча'), ('достигнута_договоренность', 'Достигнута договоренность'), ('готовится_договор', 'Готовится договор'), ('заключен_договор', 'Заключен договор'), ('исполнена_поставка', 'Исполнена поставка'), ('выполнен_монтаж', 'Выполнен монтаж'), ('идет_гарантийный_срок', 'Идет гарантийный срок'), ('послегарантийная_работа', 'Послегарантийная работа')], max_length=50, verbose_name='Состояние')),
                ('description_of_task_at_stage', models.TextField(verbose_name='Описание задач на этап')),
                ('description_of_what_has_been_achieved_at_a_stage', models.TextField(blank=True, null=True, verbose_name='Описание достигнутого на этапе')),
                ('description_of_tasks_for_our_specialists', models.TextField(blank=True, null=True, verbose_name='Описание задач для наших специалистов')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='этапы_сделки', to='crm.deal', verbose_name='Сделка')),
                ('our_specialists_involved', models.ManyToManyField(blank=True, related_name='этапы_сделки', to=settings.AUTH_USER_MODEL, verbose_name='Привлекаемые наши специалисты')),
            ],
            options={
                'verbose_name': 'Этап сделки',
                'verbose_name_plural': 'Этапы сделки',
                'ordering': ['start_date_step'],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='name_of_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.prouct', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='deal',
            name='responsible_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер'),
        ),
    ]
