# Generated by Django 4.2.23 on 2025-07-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='shipping_address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес отгрузки'),
        ),
        migrations.AlterField(
            model_name='decision_maker',
            name='email',
            field=models.EmailField(blank=True, max_length=54, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='decision_maker',
            name='function',
            field=models.IntegerField(choices=[(0, 'директор'), (1, 'главный инженер'), (2, 'технический специалист')], default=0, verbose_name='Роль'),
        ),
    ]
