# Generated by Django 4.2.23 on 2025-07-14 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0002_alter_deal_shipping_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prouct',
            new_name='Product',
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField(verbose_name='Плановая дата')),
                ('letter_file', models.FileField(upload_to='letters/', verbose_name='Тело письма')),
                ('incoming_number', models.CharField(max_length=50, verbose_name='Входящий номер заказчика')),
                ('incoming_date', models.DateField(verbose_name='Входящая дата заказчика')),
                ('responsible_person_from_customer', models.CharField(max_length=100, verbose_name='Ответственный от заказчика')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer', verbose_name='Заказчик')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.deal', verbose_name='Сделка')),
                ('decision_maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.decision_maker', verbose_name='ЛПР')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
                'ordering': ['-planned_date'],
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField(verbose_name='Плановая дата')),
                ('call_goal', models.CharField(max_length=200, verbose_name='Описание цели звонка')),
                ('call_result', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание результата')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer', verbose_name='Заказчик')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.deal', verbose_name='Сделка (если есть)')),
                ('decision_maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.decision_maker', verbose_name='ЛПР')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Звонок',
                'verbose_name_plural': 'Звонки',
                'ordering': ['-planned_date'],
            },
        ),
    ]
