# Generated by Django 4.2.23 on 2025-07-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_rename_prouct_product_letter_call'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании')),
                ('revenue_for_last_year', models.DecimalField(decimal_places=2, help_text='Миллиард рублей', max_digits=12, verbose_name='Выручка за последний год')),
                ('length_of_electrical_network_km', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Длина сетей, км')),
                ('quantity_of_technical_transformer_pcs', models.PositiveIntegerField(verbose_name='Количество ТП, шт')),
                ('address', models.TextField(verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиал',
                'ordering': ['name_of_company'],
            },
        ),
    ]
