# Generated by Django 4.2.23 on 2025-07-18 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0004_company_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_branch',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='crm.customer', verbose_name='Родительский заказчик'),
        ),
        migrations.AlterField(
            model_name='call',
            name='call_goal',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание цели звонка'),
        ),
        migrations.AlterField(
            model_name='call',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customer', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='call',
            name='decision_maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.decision_maker', verbose_name='ЛПР'),
        ),
        migrations.AlterField(
            model_name='call',
            name='planned_date',
            field=models.DateField(blank=True, null=True, verbose_name='Плановая дата'),
        ),
        migrations.AlterField(
            model_name='company_branch',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='company_branch',
            name='length_of_electrical_network_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Длина сетей, км'),
        ),
        migrations.AlterField(
            model_name='company_branch',
            name='name_of_company',
            field=models.CharField(default='Без названия', max_length=255, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='company_branch',
            name='quantity_of_technical_transformer_pcs',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество ТП, шт'),
        ),
        migrations.AlterField(
            model_name='company_branch',
            name='revenue_for_last_year',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Миллиард рублей', max_digits=12, null=True, verbose_name='Выручка за последний год'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='length_of_electrical_network_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Длина сетей, км'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name_of_company',
            field=models.CharField(default='Без названия', max_length=255, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='quantity_of_technical_transformer_pcs',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество ТП, шт'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='revenue_for_last_year',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Миллиард рублей', max_digits=12, null=True, verbose_name='Выручка за последний год'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='сделки', to='crm.customer', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='date_of_last_change',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='date_of_next_activity',
            field=models.DateField(blank=True, null=True, verbose_name='Дата следующей активности'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='deal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Сумма сделки'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='quantity_of_all_product',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Количество всех продуктов, шт'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(blank=True, choices=[('подготовлен_звонок', 'Подготовлен звонок'), ('сделан_звонок', 'Сделан звонок'), ('назначена_встреча', 'Назначена встреча'), ('прошла_встреча', 'Прошла встреча'), ('достигнута_договоренность', 'Достигнута договоренность'), ('готовится_договор', 'Готовится договор'), ('заключен_договор', 'Заключен договор'), ('исполнена_поставка', 'Исполнена поставка'), ('выполнен_монтаж', 'Выполнен монтаж'), ('идет_гарантийный_срок', 'Идет гарантийный срок'), ('послегарантийная_работа', 'Послегарантийная работа')], max_length=50, null=True, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='deal_stage',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='этапы_сделки', to='crm.deal', verbose_name='Сделка'),
        ),
        migrations.AlterField(
            model_name='deal_stage',
            name='description_of_task_at_stage',
            field=models.TextField(blank=True, null=True, verbose_name='Описание задач на этап'),
        ),
        migrations.AlterField(
            model_name='deal_stage',
            name='end_date_step',
            field=models.DateField(blank=True, null=True, verbose_name='Дата конца этапа'),
        ),
        migrations.AlterField(
            model_name='deal_stage',
            name='our_specialists_involved',
            field=models.ManyToManyField(blank=True, default=0, related_name='этапы_сделки', to=settings.AUTH_USER_MODEL, verbose_name='Привлекаемые наши специалисты'),
        ),
        migrations.AlterField(
            model_name='deal_stage',
            name='start_date_step',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала этапа'),
        ),
        migrations.AlterField(
            model_name='deal_stage',
            name='status',
            field=models.CharField(blank=True, choices=[('подготовлен_звонок', 'Подготовлен звонок'), ('сделан_звонок', 'Сделан звонок'), ('назначена_встреча', 'Назначена встреча'), ('прошла_встреча', 'Прошла встреча'), ('достигнута_договоренность', 'Достигнута договоренность'), ('готовится_договор', 'Готовится договор'), ('заключен_договор', 'Заключен договор'), ('исполнена_поставка', 'Исполнена поставка'), ('выполнен_монтаж', 'Выполнен монтаж'), ('идет_гарантийный_срок', 'Идет гарантийный срок'), ('послегарантийная_работа', 'Послегарантийная работа')], max_length=50, null=True, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='decision_maker',
            name='city_of_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город местонахождения'),
        ),
        migrations.AlterField(
            model_name='decision_maker',
            name='function',
            field=models.IntegerField(blank=True, choices=[(0, 'директор'), (1, 'главный инженер'), (2, 'технический специалист')], default=0, null=True, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='decision_maker',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customer', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='decision_maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.decision_maker', verbose_name='ЛПР'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='incoming_date',
            field=models.DateField(blank=True, null=True, verbose_name='Входящая дата заказчика'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='incoming_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Входящий номер заказчика'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_file',
            field=models.FileField(blank=True, null=True, upload_to='letters/', verbose_name='Тело письма'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='planned_date',
            field=models.DateField(blank=True, null=True, verbose_name='Плановая дата'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='responsible_person_from_customer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ответственный от заказчика'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_customer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена для конечного заказчика'),
        ),
    ]
