# Generated by Django 5.1.11 on 2025-12-29 13:29

import django.db.models.deletion
import django.utils.timezone
import shared_repository.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedRepository',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('document_title', models.CharField(help_text='Все текстовые символы - 100 символов max', max_length=100, unique=True, verbose_name='Название документа')),
                ('date_of_creation', models.DateTimeField(default=django.utils.timezone.now, help_text='Формат: YYYY-MM-DD HH:MI:SS', verbose_name='Дата и время создания')),
                ('date_of_change', models.DateTimeField(auto_now=True, help_text='Формат: YYYY-MM-DD HH:MI:SS', verbose_name='Дата и время последнего изменения')),
                ('version', models.CharField(default='1', help_text='Цифры, 3 символа max', max_length=3, verbose_name='Версия')),
                ('uploaded_file', models.FileField(help_text='Текст, строго в соответствии с данными в колонке "Визуализация"', upload_to='shared_repository/documents/%Y/%m/%d/', validators=[shared_repository.models.validate_file_size], verbose_name='Загружаемый файл')),
                ('document_purpose', models.TextField(blank=True, help_text='Все текстовые символы - 5000 символов max', max_length=5000, null=True, verbose_name='Назначение документа')),
                ('author', models.ForeignKey(help_text='Имя пользователя системы (ссылка на User)', on_delete=django.db.models.deletion.PROTECT, related_name='authored_documents', to=settings.AUTH_USER_MODEL, verbose_name='Создатель (автор)')),
                ('current_responsible', models.ForeignKey(help_text='Имя пользователя системы (ссылка на User)', on_delete=django.db.models.deletion.PROTECT, related_name='responsible_documents', to=settings.AUTH_USER_MODEL, verbose_name='Текущий ответственный')),
                ('last_editor', models.ForeignKey(help_text='Имя пользователя системы (ссылка на User)', on_delete=django.db.models.deletion.PROTECT, related_name='last_edited_documents', to=settings.AUTH_USER_MODEL, verbose_name='Последний редактор')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-date_of_creation'],
            },
        ),
    ]
